In [1]:
import json
import numpy as np
import copy

In [2]:
def JSON_to_Dictonary(filename):
    """
    Converts JSON to Dictonary with one timestamp of lidar data

    Parameters
    ----------
    filename : string
        .json of lidar data

    Returns
    -------
    dictonary
    {
        point_cloud = [num_of_points][3],
        pose :
            orientation :
                w_val = num,
                x_val = num,
                y_val = num,
                z_val = num
            position :
                x_val = num,
                y_val = num,
                z_val = num

    }
    """

    with open(filename) as f:
        data = json.load(f)

        # get first timestamp
        if 'point_cloud' not in data.keys():
            data = next(iter(data.values()))

    return data

In [3]:
def calculate_rotation(data):
    """
    Rotate a point cloud based on drone orientation

    Parameters
    ----------
    data : dictonary

    Returns
    -------
    data : dictonary
        Only data["point_cloud"] is changed
    """

    return data

In [9]:
def calculate_offset(data):
    """
    Offset a point cloud based on drone position

    Parameters
    ----------
    data : dictonary

    Returns
    -------
    data : dictonary
        Only data["point_cloud"] is changed
    """
    data["point_cloud"] += np.array(list(data["pose"]["position"].values()))

    return data

In [10]:
def transform_data(data):
    """
    Transforms a point cloud based on drone's orientation and position

    Parameters
    ----------
    data : dictonary

    Returns
    -------
    point_cloud
        [num_of_points][3]
    """

    rotated_data = calculate_rotation(data)
    transformed_data = calculate_offset(rotated_data)
    point_cloud = transformed_data["point_cloud"]
    
    return point_cloud

In [11]:
def point_cloud_to_occupancy_map(point_cloud, z_range, grid_size, resolution):
    """
    Convert a point cloud into an occupancy map

    Parameters
    ----------
    point_cloud : [num_of_points][3]
    z_range : (z_min, z_max)
    grid_size : (width, height)
    resolution : meters per grid cell

    Returns
    -------
    2d binary list of grid_size
    """

    return [
        [ 0, 0, 0 ],
        [ 1, 1, 0 ]
    ]

In [14]:
def JSON_to_Occupancy_Map(filename, z_range, grid_size, resolution):
    data = JSON_to_Dictonary(filename)
    point_cloud = transform_data(data)
    occupancy_map = point_cloud_to_occupancy_map(point_cloud, z_range, grid_size, resolution)
    return occupancy_map

In [15]:
JSON_to_Occupancy_Map('lidar_data_sample_boxed_env.json', (-5, -4), (200, 200), 1)

[[12.         -3.95295501 -3.74695921]
 [12.         -3.81976414 -3.74695921]
 [12.         -3.68742228 -3.74695921]
 ...
 [11.19849777  3.76943588 -9.25679398]
 [11.16006565  3.88173771 -9.25679398]
 [11.12051201  3.99364853 -9.25679398]]


[[0, 0, 0], [1, 1, 0]]